# Generated by Django 2.0.6 on 2018-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_auto_20180814_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='banda'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='integrante'),
        ),
    ]
