# Generated by Django 2.0.6 on 2018-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_auto_20180814_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=2),
        ),
    ]
