# Generated by Django 2.0.6 on 2018-08-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_auto_20180823_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='nombre',
        ),
    ]
