# Generated by Django 2.0.6 on 2018-08-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_auto_20180823_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2),
        ),
    ]
