# Generated by Django 2.0.6 on 2018-08-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_auto_20180830_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre',
            new_name='user',
        ),
    ]
